# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  Glad_config = debug
  Mandlebrot_config = debug

else ifeq ($(config),release)
  GLFW_config = release
  Glad_config = release
  Mandlebrot_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW Glad Mandlebrot

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C vendor/GLFW -f Makefile config=$(GLFW_config)
endif

Glad:
ifneq (,$(Glad_config))
	@echo "==== Building Glad ($(Glad_config)) ===="
	@${MAKE} --no-print-directory -C vendor/Glad -f Makefile config=$(Glad_config)
endif

Mandlebrot: GLFW Glad
ifneq (,$(Mandlebrot_config))
	@echo "==== Building Mandlebrot ($(Mandlebrot_config)) ===="
	@${MAKE} --no-print-directory -C Mandlebrot -f Makefile config=$(Mandlebrot_config)
endif

clean:
	@${MAKE} --no-print-directory -C vendor/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C vendor/Glad -f Makefile clean
	@${MAKE} --no-print-directory -C Mandlebrot -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   Glad"
	@echo "   Mandlebrot"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"